### ISSUE TITLE
Does not work with non US-Layout keyboards

### ISSUE THREAD

**Issue by CodeBrauer** [thundertick/thundertick#2]
In my case I'm using a [German layout](http://i.stack.imgur.com/ErgQC.jpg).

IMHO there should be a option to define your own keystroke to call thundertick.

Also bear in mind of the windows and mac differences.

**Comment by yannbertrand** [comment]
Same problem with French AZERTY

**Comment by Manak** [comment]
You guys right! the next version will allow to setup a custom hotkey instead of relying solely on the backtick. Should be up soon.

**Comment by ghost** [comment]
same as yann, not working with a french azerty

**Comment by Manak** [comment]
Thundertick has been updated to v1.5.0!
You can now set a custom hotkey for launching thundertick by going into it's chrome options page. You can access the settings page by right clicking on the thundertick icon in your chrome toolbar and clicking the `options` button!
This should resolve the problems people, with alternate keyboard layouts, have been facing.
