### ISSUE TITLE
Backtick keystroke with US-international English keyboard layout

### ISSUE THREAD

**Issue by lawgsy** [thundertick/thundertick#6]
It appears that, since the backtick is a modifier rather than a direct keystroke with the US-international English keyboard layout, that the key is not actually sent (yet thundertick comes up).

The issue is that once you start typing in the thundertick window, the backtick appears and corrupts the command you input (you have to go back and remove the backtick, or press `backspace` right after pressing the backtick every time.

A decent alternative appears to be using the `tab` key. I suggest somehow blocking the backtick (or other key) being pressed though, as in not allowing the keypress to be passed through to the browser (blocking it) while the plugin has it set as it's activator.

**Comment by Manak** [comment]
This should've been fixed with v1.5.0 which allows you to set the hotkey to any key 😃
